### ISSUE TITLE
Datadog or Papertrail

### ISSUE THREAD

**Issue by jeffmacdonald** [apiaryio/cloudwatch-to-papertrail#10]
Hi,

Sort of a question more than an issue.. how does datadog fit into this mix? Is this more than just shipping cloudwatch lots to papertrail?

Thanks.

**Comment by w-vi** [comment]
Hi actually yes, if the log entry is formatted in certain way we treat it as a metric entry and push it to datadog. See our heroku to datadog log drain for more details. https://github.com/apiaryio/heroku-datadog-drain-golang#custom-metrics I guess we should maybe document the whole thing nicely so it makes sense to everybody not just us.

**Comment by jeffmacdonald** [comment]
Thanks for the quick answer! The documentation is welcome, as it appears this tool is exactly what we need. I might be asking you a few more :) Is there a better place to ask or is github issues fine?

**Comment by pksunkara** [comment]
Github issues is fine.
