### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by tdmalone** [apiaryio/cloudwatch-to-papertrail#13]
Hi there,

Thank you for putting this together!

Given that you've put it up here on GitHub and with a detailed README, I'm assuming you're ok for others to use this.

Would you mind adding a license to the repo to make your intentions clear?

You can find out more at https://choosealicense.com/, or I'd be happy to send a PR with a license if you can suggest what you would consider most appropriate.

Thanks! :)

**Comment by w-vi** [comment]
@tdmalone Thanks for pointing this out, we complain about missing licenses and are guilty as well 🤦‍♂️ 
Hope that now it is solved for you.
