### ISSUE TITLE
Move it to nodejs4.3 environment

### ISSUE THREAD

**Issue by w-vi** [apiaryio/cloudwatch-to-papertrail#5]
It uses 0.10 node environment on AWS lambda which is suboptimal and has some issues, like event loop not finishing etc.

**Comment by pksunkara** [comment]
Node 4.3 was having some issues with sending the data completely.

**Comment by w-vi** [comment]
Strange but still worth investigating wasn't the `callbackWaitsForEmptyEventLoop` somehow involved?

http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html

**Comment by w-vi** [comment]
Closed by #8
